From Demo To MyDev/sample/retrieveSource/objects/PartnerIndex__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Партнер</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Показатели</relationshipLabel>
        <relationshipName>AccountIndexes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IndexDate__c</fullName>
        <label>Период показателя</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IndexShortDate__c</fullName>
        <formula>CASE(MONTH(IndexDate__c), 
  1, &quot;01.&quot;, 
  2, &quot;02.&quot;,
  3, &quot;03.&quot;,
  4, &quot;04.&quot;,
  5, &quot;05.&quot;,
  6, &quot;06.&quot;,
  7, &quot;07.&quot;,
  8, &quot;08.&quot;,
  9, &quot;09.&quot;,
  10, &quot;10.&quot;,
  11, &quot;11.&quot;,
  12, &quot;12.&quot;,
  &quot;&quot;) +  TEXT(YEAR(IndexDate__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Период показателя</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PercentSalesVolumeFact__c</fullName>
        <formula>PeriodSalesVolumeFact__c / PeriodSalesVolumePlan__c</formula>
        <label>% выполнения объема продаж НСЖ</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PeriodSalesVolumeFact__c</fullName>
        <label>Объём продаж НСЖ (факт)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodSalesVolumeInvestFact__c</fullName>
        <label>Объём продаж ИСЖ (факт)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodSalesVolumeInvestPlan__c</fullName>
        <label>Объём продаж ИСЖ (план)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PeriodSalesVolumePlan__c</fullName>
        <label>Объём продаж НСЖ (план)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Причина</label>
        <type>TextArea</type>
    </fields>
    <label>Показатель</label>
    <nameField>
        <displayFormat>I-{000}</displayFormat>
        <label>Код</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Показатели</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DemoMetadata/unpackaged/classes/PartnerIndexController.cls
public class PartnerIndexController {
    
    @AuraEnabled
    public static List<PartnerIndex__c> getPartnerIndex(ID accId) {
        
        return [SELECT id,IndexShortDate__c,Name,IndexDate__c,
                PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                PercentSalesVolumeFact__c, PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c FROM PartnerIndex__c WHERE Account__c	 = :accId ORDER BY IndexDate__c];
        
        
    }  

    @AuraEnabled
    public static List<PartnerIndex__c> getPartIndNow(ID accId) {
        Date qwe = System.today();
        return [SELECT id,IndexShortDate__c,Name,IndexDate__c,
                PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                PercentSalesVolumeFact__c, PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c FROM PartnerIndex__c WHERE (Account__c = :accId AND CALENDAR_YEAR(IndexDate__c)=:qwe.year()) ORDER BY IndexDate__c LIMIT 12];
 
    } 

     @AuraEnabled
    public static List<PartnerIndex__c> getPartIndAll(ID accId) {
        return [SELECT id,IndexShortDate__c,Name,IndexDate__c,
                PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                PercentSalesVolumeFact__c, PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c FROM PartnerIndex__c WHERE Account__c = :accId  ORDER BY IndexDate__c ];
 
    }
    


    
    @AuraEnabled
    public static List<PartnerIndex__c>  createPartnerIndex (ID accId) {
        Date qwe = System.today();
        Integer currentYearI =  System.Today().year();
        String currentYearS = String.valueOf(currentYearI);
        // Date currentYear = Date.newInstance(currentYearS, '1', '1');
        List<PartnerIndex__c>  oldpartnerList = [SELECT id,IndexShortDate__c,Name, IndexDate__c,
                                                 PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                                                 PercentSalesVolumeFact__c,PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c, Account__c FROM PartnerIndex__c WHERE (Account__c = :accId AND CALENDAR_YEAR(IndexDate__c)=:qwe.year()) ORDER BY IndexDate__c LIMIT 12]; 
        
        //system.debug('old: ' + oldpartnerList);
        
        if (oldpartnerList.IsEmpty()){
		
        Date newdate = date.newInstance(System.today().year(), 1, 1);
        List<PartnerIndex__c> newpartnerList = new List<PartnerIndex__C>();
        	
            
            PartnerIndex__c p1 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(0));
            PartnerIndex__c p2 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(1));
            PartnerIndex__c p3 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(2));
            PartnerIndex__c p4 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(3));
            PartnerIndex__c p5 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(4));
            PartnerIndex__c p6 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(5));
            PartnerIndex__c p7 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(6) );
            PartnerIndex__c p8 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(7));
            PartnerIndex__c p9 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(8));
            PartnerIndex__c p10 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(9));
            PartnerIndex__c p11 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(10));
            PartnerIndex__c p12 = new PartnerIndex__c(Account__c = accId, IndexDate__c = newdate.addMonths(11));
           	
        	newpartnerList.add(p1);
            newpartnerList.add(p2);
            newpartnerList.add(p3);
            newpartnerList.add(p4);
            newpartnerList.add(p5);
            newpartnerList.add(p6);
            newpartnerList.add(p7);
            newpartnerList.add(p8);
            newpartnerList.add(p9);
            newpartnerList.add(p10);
            newpartnerList.add(p11);
            newpartnerList.add(p12);
            
            insert newpartnerList;
   
        }else
        {
          // System.debug('not empty');  
        }

        
        Date qwe1 = qwe.addYears(1);
        
        List<PartnerIndex__c>  nextypartnerList = [SELECT id,IndexShortDate__c,Name, IndexDate__c,
                                                   PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                                                   PercentSalesVolumeFact__c,PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c, Account__c FROM PartnerIndex__c WHERE (Account__c = :accId AND CALENDAR_YEAR(IndexDate__c)=:qwe1.year()) ORDER BY IndexDate__c LIMIT 12]; 
        
        
        if (nextypartnerList.IsEmpty())
        {
            List <PartnerIndex__c> newpartnerList = new  List<PartnerIndex__c>();
            
            for (PartnerIndex__c item : oldpartnerList){
                PartnerIndex__c newItem = new PartnerIndex__c();
                newItem.IndexDate__c = item.IndexDate__c.addYears(1);
                //newItem.IndexShortDate__c = item.IndexShortDate__c;
                newItem.PeriodSalesVolumePlan__c = item.PeriodSalesVolumePlan__c;
                newItem.Account__c = item.Account__c;
                newpartnerList.add(newItem);
            }
            //system.debug('new: ' + newpartnerList);
            insert newpartnerList;
            
        }
        else
        {
           // System.debug('not empty');
        }
        
        
        
        return [SELECT id,IndexShortDate__c,Name,IndexDate__c,
                PeriodSalesVolumePlan__c, PeriodSalesVolumeFact__c,
                PercentSalesVolumeFact__c,PeriodSalesVolumeInvestFact__c, PeriodSalesVolumeInvestPlan__c FROM PartnerIndex__c WHERE Account__c	 = :accId ORDER BY 	IndexDate__c]; 
        
    }   
    
    @AuraEnabled
    public static List<PartnerIndex__c> getIndex(ID partnerId) {
        
        return [SELECT Reason__c, PeriodSalesVolumePlan__c FROM PartnerIndex__c WHERE Id = :partnerId];
    }
    
    @AuraEnabled
    public static boolean upsertIndex(List<PartnerIndex__c> IndexList){
        //System.debug('index: ' + IndexList[0]);
        PartnerIndex__c qwe = IndexList[0];
        System.debug('reason= ' + qwe);
        if (qwe.Reason__c == NULL)
        {
            return false;
        }
        else
        {
            try{
                upsert IndexList;
                return true;
            } catch(Exception e){
                return false;
            } 
            
        }
        
    }
    
    
}